version: '3.8'

services:
  database:
    image: postgres:15
    container_name: financetrack-db
    restart: always
    environment:
      POSTGRES_DB: financetrack_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_/var/lib/postgresql/data
    networks:
      - financetrack-network

  redis:
    image: redis:7-alpine
    container_name: financetrack-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - financetrack-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: financetrack-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - financetrack-network

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: financetrack-backend
    ports:
      - "3001:3000"
    volumes:
      - ../backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/financetrack_dev
      - REDIS_URL=redis://redis:6379
    depends_on:
      - database
      - redis
    networks:
      - financetrack-network

volumes:
  postgres_

networks:
  financetrack-network:
    driver: bridge